name = "app"
version = "0.1.0"
defaultTargets = ["app"]

[[lean_lib]]
name = "app"
srcDir = "extraction"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[require]]
name = "leaf_a"
path = "../../../leaf_a/proofs/lean/"

[[require]]
name = "leaf_b"
path = "../../../leaf_b/proofs/lean/"