-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [simple]: function definitions
import Aeneas
import CoreModels
import Simple.Extraction.Types
import Simple.Extraction.FunsExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace simple

/-- [simple::add_u32]:
    Source: 'src/lib.rs', lines 15:0-17:1
    Visibility: public -/
def add_u32 (a : Std.U32) (b : Std.U32) : RustM Std.U32 := do
  a + b

/-- [simple::double_u32]:
    Source: 'src/lib.rs', lines 22:0-24:1
    Visibility: public -/
def double_u32 (x : Std.U32) : RustM Std.U32 := do
  add_u32 x x

/-- [simple::max_u32]:
    Source: 'src/lib.rs', lines 28:0-34:1
    Visibility: public -/
def max_u32 (a : Std.U32) (b : Std.U32) : RustM Std.U32 := do
  if a >= b
  then ok a
  else ok b

end simple
