-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [simple]: proof obligations
import Aeneas
import CoreModels
import Simple.Extraction.Types
import Simple.Extraction.Funs
import Simple.Extraction.Specs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace simple

@[spec]
theorem add_u32.spec.proof (a : Std.U32) (b : Std.U32) : add_u32.spec a b
  := by sorry

@[spec]
theorem double_u32.spec.proof (x : Std.U32) : double_u32.spec x := by sorry

@[spec]
theorem max_u32.spec.proof (a : Std.U32) (b : Std.U32) : max_u32.spec a b
  := by sorry

end simple
