-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [simple]: specs (statements of correctness)
import Aeneas
import CoreModels
import Hax
import Simple.Extraction.Types
import Simple.Extraction.Funs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace simple


/-- [simple::add_u32::pre]:
    Source: 'src/lib.rs', lines 13:0-13:39 -/
@[reducible]
def add_u32.pre (a : Std.U32) (b : Std.U32) : RustM Bool := do
  let i ← core.num.U32.MAX - b
  ok (a <= i)

/-- [simple::add_u32::post]:
    Source: 'src/lib.rs', lines 14:0-14:66 -/
@[reducible]
def add_u32.post (a : Std.U32) (b : Std.U32) (res : Std.U32) : RustM Bool := do
  let i ← hax_lib.U32.Insts.Hax_libIntToInt.to_int res
  let i1 ← hax_lib.U32.Insts.Hax_libIntToInt.to_int a
  let i2 ← hax_lib.U32.Insts.Hax_libIntToInt.to_int b
  let i3 ← hax_lib.int.Int.Insts.CoreOpsArithAddIntInt.add i1 i2
  hax_lib.int.Int.Insts.CoreCmpPartialEqInt.eq i i3

def add_u32.spec (a : Std.U32) (b : Std.U32) : Prop :=
  (add_u32.pre a b).holds →
  ⦃ ⌜ True ⌝ ⦄
  add_u32 a b
  ⦃ ⇓ res => ⌜ (add_u32.post a b res).holds ⌝ ⦄


/-- [simple::double_u32::pre]:
    Source: 'src/lib.rs', lines 20:0-20:39 -/
@[reducible]
def double_u32.pre (x : Std.U32) : RustM Bool := do
  let i ← core.num.U32.MAX / 2#u32
  ok (x <= i)

/-- [simple::double_u32::post]:
    Source: 'src/lib.rs', lines 21:0-21:66 -/
@[reducible]
def double_u32.post (x : Std.U32) (res : Std.U32) : RustM Bool := do
  let i ← hax_lib.U32.Insts.Hax_libIntToInt.to_int res
  let i1 ← hax_lib.U32.Insts.Hax_libIntToInt.to_int x
  let i2 ← hax_lib.int.Int.Insts.CoreOpsArithAddIntInt.add i1 i1
  hax_lib.int.Int.Insts.CoreCmpPartialEqInt.eq i i2

def double_u32.spec (x : Std.U32) : Prop :=
  (double_u32.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  double_u32 x
  ⦃ ⇓ res => ⌜ (double_u32.post x res).holds ⌝ ⦄


/-- [simple::max_u32::post]:
    Source: 'src/lib.rs', lines 27:0-27:73 -/
@[reducible]
def max_u32.post (a : Std.U32) (b : Std.U32) (res : Std.U32) : RustM Bool := do
  if res >= a
  then if res >= b
       then if res = a
            then ok true
            else ok (res = b)
       else ok false
  else ok false

def max_u32.spec (a : Std.U32) (b : Std.U32) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  max_u32 a b
  ⦃ ⇓ res => ⌜ (max_u32.post a b res).holds ⌝ ⦄

end simple
