-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [simple]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace simple

/-- [simple::add_u32]:
    Source: 'src/lib.rs', lines 6:0-8:1
    Visibility: public -/
def add_u32 (a : Std.U32) (b : Std.U32) : Result Std.U32 := do
  a + b

/-- [simple::double_u32]:
    Source: 'src/lib.rs', lines 11:0-13:1
    Visibility: public -/
def double_u32 (x : Std.U32) : Result Std.U32 := do
  add_u32 x x

/-- [simple::max_u32]:
    Source: 'src/lib.rs', lines 16:0-22:1
    Visibility: public -/
def max_u32 (a : Std.U32) (b : Std.U32) : Result Std.U32 := do
  if a >= b
  then ok a
  else ok b

end simple
